package com.example.mini_bank.enums;

public enum ErrorCode {
	USER_NOT_FOUND,
    CARD_NOT_FOUND,
    TRANSACTION_NOT_FOUND,
    INSUFFICIENT_FUNDS,
    CARD_BLOCKED,
    CARD_INACTIVE,
    INVALID_CARD_STATUS,
    UNAUTHORIZED,
    ACCESS_DENIED,
    INVALID_REQUEST,
    DUPLICATE_OPERATION,
    INTERNAL_ERROR
}
